Full cleanup
Patch set 2:  A few escaped my gaze...
Patch set 3:  That does it, all fixed up!
Patch set 4:  THAT fixed it!  Sorry about that

Change-Id: Idd22cd842e9a8fcea1e2c899cd2855338f9d1f4c

diff --git a/tools/squisher b/tools/squisher
--- a/tools/squisher
+++ b/tools/squisher
@@ -21,8 +21,8 @@ else
 fi
 
 if [ -z "$OUT" -o ! -d "$OUT" ]; then
-	echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
-	exit 1
+    echo -e $CL_RED"ERROR: $0 only works with a full build environment. $OUT should exist."$CL_RST
+    exit 1
 fi
 
 if [ "$TARGET_BUILD_TYPE" = "debug" ]; then
@@ -34,8 +34,8 @@ else
     OTAPACKAGE=$OUT/$TARGET_PRODUCT-ota-eng.$USER.zip
 fi
 if [ ! -f "$OTAPACKAGE" ]; then
-	echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
-	exit 1
+    echo -e $CL_RED"$OTAPACKAGE doesn't exist!"$CL_RST;
+    exit 1
 fi
 
 OPTICHARGER=$ANDROID_BUILD_TOP/vendor/vanir/tools/opticharger
@@ -44,31 +44,31 @@ DELETE_BINS="applypatch applypatch_static check_prereq recovery updater"
 
 # Some products want a squashfs for xbin for space
 case "$TARGET_PRODUCT" in
-	cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
-	*) WANT_SQUASHFS=0 ;;
+    cyanogen_dream_sapphire) WANT_SQUASHFS=1 ;;
+    *) WANT_SQUASHFS=0 ;;
 esac
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	fatal=0
-	MKSQUASHFS_VER_REQ=4
-	if type mksquashfs >/dev/null 2>&1; then
-		if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
-			echo
-			echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
-			fatal=1
-		fi
-	else
-		echo
-		echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
-		fatal=1
-	fi
+    fatal=0
+    MKSQUASHFS_VER_REQ=4
+    if type mksquashfs >/dev/null 2>&1; then
+        if mksquashfs -version | grep -q "version $MKSQUASHFS_VER_REQ"; then :; else
+            echo
+            echo "ERROR: mksquashfs must be at least version $MKSQUASHFS_VER_REQ for this build."
+                fatal=1
+            fi
+        else
+            echo
+            echo "ERROR: $TARGET_PRODUCT requires mksquashfs."
+            fatal=1
+        fi
 
-	if [ "$fatal" -ne 0 ]; then
-		echo
-		echo "       Unoptimized package is still available at"
-		echo "         $OTAPACKAGE"
-		exit $fatal
-	fi
+        if [ "$fatal" -ne 0 ]; then
+            echo
+            echo "       Unoptimized package is still available at"
+            echo "         $OTAPACKAGE"
+            exit $fatal
+        fi
 fi
 
 REPACK=$OUT/repack.d
@@ -95,7 +95,7 @@ cp $REPACK/ota/system/framework/framework-res.apk .
 cp $REPACK/ota/system/app/*.apk .
 
 # Do optimization in parallel
-find ./ -name \*.apk | $XARGS $OPTICHARGER 
+find ./ -name \*.apk | $XARGS $OPTICHARGER
 
 # Move optimized apks to repack directory
 mv -f $REPACK/parallel/framework-res.apk $REPACK/ota/system/framework/framework-res.apk
@@ -108,38 +108,38 @@ rm -rf $REPACK/parallel
 
 
 if [ "$WANT_SQUASHFS" -eq 1 ]; then
-	squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
-	updater=$REPACK/ota/META-INF/com/google/android/updater-script
+    squash_opts="-force-uid 1000 -force-gid 1000 -no-progress -noappend -no-exports -no-recovery"
+    updater=$REPACK/ota/META-INF/com/google/android/updater-script
 
-	# Relocate su
-	cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
-	rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
-	mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
-	chmod -R 555 $REPACK/_xbin/*
+    # Relocate su
+    cp -a $REPACK/ota/system/xbin $REPACK/_xbin/
+    rm -f $REPACK/_xbin/su $REPACK/ota/system/bin/su
+    mv $REPACK/ota/system/xbin/su $REPACK/ota/system/bin/su
+    chmod -R 555 $REPACK/_xbin/*
 
-	# Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
-	# Forgive me for the regex hell here.
-	ln -s ../bin/su $REPACK/_xbin/su
-	for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
-	do
-		ln -s busybox $REPACK/_xbin/$link
-	done
+    # Create symlinks for su and busybox (since updater-script can't work on the squashfs filesystem).
+    # Forgive me for the regex hell here.
+    ln -s ../bin/su $REPACK/_xbin/su
+    for link in `sed -n -e's/,//g' -e'/symlink(.*busybox/,/xbin.*);/p' $updater | tr '"' '\n' | sed -n -e'\,/system/xbin/,s,/system/xbin/,,p'`
+    do
+        ln -s busybox $REPACK/_xbin/$link
+    done
 
-	# Create the squashfs with new and improved symlinkage!
-	mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
-	rm -rf $REPACK/ota/system/xbin/*
-	mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
-	chmod 444 $REPACK/ota/system/xbin/xbin.sqf
+    # Create the squashfs with new and improved symlinkage!
+    mksquashfs $REPACK/_xbin/* $REPACK/_xbin.sqf $squash_opts
+    rm -rf $REPACK/ota/system/xbin/*
+    mv $REPACK/_xbin.sqf $REPACK/ota/system/xbin/xbin.sqf
+    chmod 444 $REPACK/ota/system/xbin/xbin.sqf
 
-	# Remove xbin stuff and fix up updater-script
-	$SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
+    # Remove xbin stuff and fix up updater-script
+    $SED -i -e's,system/xbin/su,system/bin/su,g' -e'/xbin/d' $updater
 fi
 
 # Fix build.prop
 $SED -i \
-	-e '/ro\.kernel\.android\.checkjni/d' \
-	-e '/ro\.build\.type/s/eng/user/' \
-	$REPACK/ota/system/build.prop
+     -e '/ro\.kernel\.android\.checkjni/d' \
+     -e '/ro\.build\.type/s/eng/user/' \
+     $REPACK/ota/system/build.prop
 	
 # Fix build.prop step 2
 echo "Fixing \"move hyst\" property name... whoever put a space in it is a butthead."
@@ -156,7 +156,7 @@ rm -rf $REPACK/ota/recovery
 
 # Strip modules
 [ -d $REPACK/ota/system/lib/modules ] && \
-	find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
+    find $REPACK/ota/system/lib/modules -name "*.ko" -print0 | xargs -0 arm-eabi-strip --strip-unneeded
 
 # Fix Beats
 rm -f $REPACK/ota/system/etc/audio_effects.conf
@@ -194,9 +194,9 @@ echo
 printf "Signing package..."
 SECURITYDIR=$ANDROID_BUILD_TOP/build/target/product/security
 java -Xmx1024m \
-	-jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
-	-w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
-	$REPACK/update.zip $OUTFILE
+    -jar $ANDROID_BUILD_TOP/out/host/$OUT_TARGET_HOST/framework/signapk.jar \
+    -w $SECURITYDIR/testkey.x509.pem $SECURITYDIR/testkey.pk8 \
+    $REPACK/update.zip $OUTFILE
 echo
 printf "Cleaning up..."
 rm -rf $REPACK
@@ -224,8 +224,8 @@ ZIPSIZE=`ls -lah $OUTFILE | awk '{ print $5}' `
 echo $CL_GRN"================"$CL_RST $TARGET_PRODUCT-$TARGET_BUILD_VARIANT: $CL_RED"completed"$CL_RST $CL_GRN"================"$CL_RST
 echo ""
 echo $CL_BLU"Product name:"$CL_RST $OUTVERSION.zip
-echo $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE     " 
-echo $CL_BLU"md5:"$CL_RST $CL_YLW" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST 
+echo $CL_BLU"Package Size: "$CL_YLW"$ZIPSIZE     "
+echo $CL_BLU"md5:"$CL_RST $CL_YLW" $(cat $img.md5sum | awk '{ print $1 }')"$CL_RST
 echo $CL_BLU"Target location:"$CL_RST
 echo $CL_YLW $OUTFILE $CL_RST
 echo ""
